name: mauroofahmed
favicon: null
layout_spectrum: 0.3383634581696242
typography_spectrum: 0.9148493946995586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.978413961129263
  lightness: 0.7193154364358634
  saturation: 0.30804144660942256
  rhythmicContrast: 0.8176752480212599
purpose: []
