name: mauroofahmed
favicon: null
layout_spectrum: 0.25176
typography_spectrum: 1
title: 'mauroof '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#34525d'
    - '#546c70'
    - '#8b8f80'
    - '#bca482'
    - '#d8b186'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
